pipeline {
    agent any

   options {
  buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '3', numToKeepStr: '3')
  disableConcurrentBuilds()
  timestamps
  timeout(time: 1, unit: 'NANOSECONDS')
}

    stages {
        stage('Build') {
            steps {
                sh '''
                    echo "Building the project..."
                    pwd
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    echo "Running tests..."
                    uname -r
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    echo "Deploying the application..."
                    touch a1jones
                '''
            }
        }

        stage('Verify') {
            steps {
                sh '''
                    echo "Verifying the deployment..."
                    ls -l a1jones
                '''
            }
        }

        stage('Cleanup') {
            steps {
                sh '''
                    echo "Cleaning up..."
                    rm a1jones
                    echo "Cleanup complete"
                '''
            }
        }
    }
}
