region                = "aws_region"
bastion_ami           = "your_bastion_ami_id"
bastion_instance_type = "t2.micro"
public_subnet_id      = "your_public_subnet_id"
key_pair_name         = "your_key_pair_name"
security_group_id     = "your_security_group_id"
