---
default_shell: /bin/bash
# default_generate_ssh_key_comment: "ansible-generated on {{ ansible_hostname }}"
default_generate_ssh_key_comment: "ansible-generated for {{ item.username }}@{{ ansible_hostname }}"
